tacomeet/minishell

execute/execute.c, execute/execute_init_utils.c, execute/new_redirect.c
normal checkin
- `0`と`1`の代わりにマクロを使用
- NULL詰めで書き間違えていたところを修正
`pipe`と`redirect out`単体が機能
```
$ pwd
/minishell
$ make
...
minishell> ls -l | wc -l > res
....
minishell> ls -l | wc -l
...
```
=> `pipe`と`redirect out`単体が機能

expander/expander.c, expander/expander_env.c, expander/test/expansion_test.c
- Update: return empty string when non-existent environment variable is entered
存在しない環境変数が与えられた時、`$HOGE`なら空文字列を返すべきだが、そのまま`$HOGE`と返してしまっていたので、修正。
以下のように、途中まで普通の文字列でも環境変数のみ空文字列になるので安心！
```bash
input:echo $HOGE
{Index: 0, Level: 0, Literal:'echo'}
{Index: 1, Level: 1, Literal:''}
input:echo hello$HOGE
{Index: 0, Level: 0, Literal:'echo'}
{Index: 1, Level: 1, Literal:'hello'}
```
後のexpansionで悪さしそうな要素がまた消えました笑
```bash
$ pwd
/expnader/test
$ make
```
=> 存在しない環境変数が与えられた場合の処理を追加

builtin/builtin.h, builtin/cd.c, builtin/test/Makefile, builtin/test/builtin_test.c
実装・テストが問題ないかレビュー
`execution`でbuiltinコマンドが使えるようになり、`subshell`の挙動確認がしやすくなる
```
$ cd /minishell/builtin/test
$ make
```
=> builtinの`cd`コマンドを実装

expander/expander.c, expander/expander.h, expander/expander_splitting.c, expander/test/expansion_test.c
- Fix: prototype declare filename
- Add: basic word splitting
expansionの`word splitting`を実装
`",'`などが混じった場合はまだ実装できてません；；
wildcard処理後、`test.c main.c`みたいな文字列が来た時に、空白ごとに文字列を分解して、複数の`t_ast_node`に枝分かれするようにした。
`t_ast_node`のlevelや枝の繋がってる位置(`left, right`)など、間違ってないか確認お願いします！
=> 簡単なwordsplittingを実装

expander/expander.c, expander/expander.h, expander/expander_env.c, expander/expander_list.c, expander/expander_splitting.c, expander/expander_utils.c, expander/expander_wildcard.c, expander/test/expansion_test.c, utils/split_by_delims.c, utils/utils.h
- Update: env_lst to getenv
- Add: t_expander
- Add: t_expander to handle error
`malloc`でエラーが起きた際に、AST全てを`free`する必要が亜あるため、`t_expander`構造体にASTのrootを持たせて対応した（できてると思う）
- 環境変数をリストではなく、`getenv()`で取得するようにしました！
- エラーが起きた時に、`delete_ast_nodes()`で`free`できるようになったはず！（あざす）
=> `t_expander`構造体を定義し、各種エラー処理を追加

execute/execute.c, execute/execute.h, execute/execute_init.c, execute/execute_utils.c, test/cases/andor.txt, test/cases/pipe.txt
checkin
- 子プロセスの`exit_status`を親プロセスから獲得
- `pipe`で繋がったときの最後の`exit_status`を次の処理に引き継げるようにした
- `and_if`と`or_if`のテストを追加
追加分のテストpass！
- `subshell`の方の処理は一旦後回しにしてます！
=> `exit_status`周りの修正

expander/expander.c, expander/expander.h, expander/expander_quote.c, expander/expander_wordsplitting.c, expander/expnader_wordsplitting.c, expander/test/expansion_test.c
- Update: wordsplitting skips quotes
以下のような入力が与えられた時
```bash
$ export TEST="echo hello"
$ $TEST
hello
$ "echo hello"
bash: echo hello: command not found
```
`', "`で囲まれているか否かで、書く文字列を分割するか否かが決まる。
以前のPRでは、`', "`内の`<space><tab><newline>`も区切りとして複数の文字列に分解していたが、今回はそこを判別して正しく文字列を分解できるようにした。
上記の例のように、expander以降の処理で、入力が正しいコマンドなのか、存在しないコマンドなのか等、正しく判断できるようになる。
昨日作った`split_by_delims()`に`',"`を読み飛ばす`skip_quotes()`という関数を加えて、`split_by_delims_skip_quotes()`という関数を作った。
この2つの関数の扱いは審議。(`skip_quotes()`を追加した状態で`utils`に置くか否か等)
=> `wordsplitting`における`', "`内のスペースを区切りとして認識しない

builtin/builtin.h, builtin/pwd.c, execute/execute_utils.c, test/cases/pwd.txt
ノーマルチェック
- `pwd()`の実装
- `execution`が`pwd()`を実行する
さらなるテストパス！
```
$ cd /minishell/test
$ ./greademe.sh -c
```
=> `pwd`コマンドの追加

expander/expander.c, expander/expander.h, expander/expander_utils.c, test/cases/expansion.txt
- Add: redirect_node exoand conditions
- Update: malloc error handling
- Update: ast_node connect after wordsplitting, return NULL when inputed invalid redirect operand
- 以下のようなリダイレクトのパターンがきた時に、`expand`でエラーの判断とメッセージ表示のみを行い、処理結果として`NULL`を返すようにした。
```bash
$ echo hello > res*
bash: res*: ambiguous redirect
$ export TEST="res res2"
$ echo hello > $TEST
bash: $TEST: ambiguous redirect
$ echo hello > ""
bash: : No such file or directory
```
`execute`に渡る前にエラーの検出、表示が行えるため、`&&, ||`などが入力された場合の処理がやりやすくなりそう？
- `execute`の中に`expand`を入れる予定ではあるが、まだ色々なエラー処理や、引数の型などはガバいので、そこは合体させてから見るしかない気がします。
=> リダイレクト先の展開結果が不正な場合のエラー処理を追加

builtin/builtin.h, builtin/builtin_export.c, builtin/builtin_unset.c, execute/execute_utils.c, libft/ft_isalnum.c, libft/ft_isalpha.c
- Add: ft_isalpha, ft_isalnum
- Fix: argument type
- Add: builtin_unset
- `unset`を追加。
- `delete_env_var()`は、引数の`key`に該当する環境変数がリストに存在する場合、`free()`する関数であるが、それがリストの先頭であった場合、ちょっと扱いがめんどくさくなる。
- 先頭を`free()`してそのまま処理を続けてしまうと、後に`env`, `export`を呼び出した時に`free()`した領域を読んでしまうため、Abortする。
- そのため、`*env_vars`が`NULL`（リストが空）でない場合、リストの２番目のアドレスを`next_var`に保存しておいて、`delete_env_var()`において`free()`した環境変数が先頭の場合（`pre_var`が`NULL`）、`*env_var = next_var;`で元々の2番目のアドレスを先頭に繋ぐ必要がある。
- このコマンドできてたら、`expand`, `execute`と合わせて色々テストできそう！
- `export`, `unset`の両方で`is_valid_argument()`という関数を用いているが、`unset`の方を`util`化した方が使い勝手が良さそう。
- `export`のエラー処理が地味にミスってまして、
```bash
$ unset =
bash: unset: `=': not a valid identifier
'
$ unset TEST=test
bash: unset: `TSET=test': not a valid identifier 
```
- 引数のエラーパターンどこまで対応するか悩み中です笑笑
=> builtinの`unset`を追加

builtin/builtin.h, builtin/builtin_export.c, builtin/builtin_unset.c, builtin/is_valid_argument.c, utils/is_valid_argument.c, utils/utils.h
- Update: split is_valid_argument() to utils
- Update: allow '_'
- Update: add argument 'len' to check export key or unset argument
- `is_valid_argument()`は`export`や`unset`で共通で使えそうだったので、`utils`に移行した。
- そういえば、環境変数の`key`は`_`が許されるので、そこも許可するようにした。
- また、若干エラー処理に変更を加えた。
- `export`
```bash
$ export TEST_1="~!@%*^" 
$ export 1TEST
minishell: export: `1_TEST': not a valid identifier'
$ export TEST^*HOGE=test
export: `TEST^*HOGE=test': not a valid identifier
```
- `unset`
```bash
$ unset TEST HOGE
$ unset TEST=
minishell: export: `TEST=': not a valid identifier'
$ unset TEST=!@#&*%^
bash: !@#: event not found
$ unset TEST=!@#&*%^
minishell: export: `TEST=!@#': not a valid identifier
```
- `export`も`unset`同様のエラー処理を行えるようになった。
- 基本的に`export`は`key`のみ、`unset`は引数全体をチェックするようにした。
- …
=> `export`コマンドなどに使用していた`is_valid_argument`を`utils`に移行

execute/execute.c
下記のようなケースに対応
```
$ < file
$ < file | echo hello
```
=> リダイレクションのみのケースに対応

Makefile, builtin/builtin.h, builtin/builtin_exit.c
以下のような挙動に合わせた！
```
$ bash -c "exit a"
bash: line 0: exit: a: numeric argument required
$ echo $?
255
$ echo "2 ^ 63" | bc
9223372036854775808
$ bash -c "exit 9223372036854775808"
bash: line 0: exit: 9223372036854775808: numeric argument required
$ echo $?
255
$ bash -c "exit 9223372036854775807"
$ echo $?                           
255
```
多分、全部のMakefileが`CFLAG`になってるんですが、デフォルトの変数名が`CFLAGS`なのでそっちに統一した方がいいかもです！
=> builtinの`exit`で引数がレンジを超えた時のエラーステータスの変更

expander/expander.c, expander/expander.h, utils/utils.h
- Update: quotation status
- Remove: inlucde 'builtin.h' in utils.h
- `expand`を実行するにあたり、今見ている文字が`', "`の中にいるかどうかが大きな問題となる。
- 以前は、くっっっっそわかりづらくその状態を書いて条件分岐していたが、今回は今見ている文字の状態を表す変数`status`と`OUTSIDE`, `IN_DOUBLE_QUOTE`のようなマクロを定義して、条件分岐するようにした。
- 後、`utils.h`の中で`#include "builtin.h"`としていたせいで、コンパイルエラーが発生していたので、そこも修正。
- 前より、今見てる文字がどの状態で、どの状態の時に条件分岐するのかわかりやすくなった！
=> `', "`の中にいるかどうかを`status`とマクロで管理

minishell.c, utils/get_next_line.c, utils/get_next_line.h
以下のようなケースに対応！
```
echo "echo hello" | ./minishell
```
方法としては、`readline()`に入る前にnon-blocking（入力がない場合は待たない）の`read()`を一発かましています！
`test`ディレクトリからの`./grademe.sh`が動くようになった！！
- `isatty()`でも同様の処理ができるようなので後で見てみる...！
=> パイプで処理内容をもらった時にプロンプトを表示しないようにする

.gitignore, execute/execute.c, execute/execute.h, execute/get_cmd_path.c, execute/get_cmd_path.h, execute/test/Makefile, execute/test/execute_test.c, libft/ft_strjoin.c, libft/ft_substr.c
使用禁止関数`execvp`の代わりに`execve`の使用
- PATHを見に行くための `get_cmd_path()`を実装
- 下記のリファレンスにあるように `:`はデリミターであるだけではなく、二つ連続した時にはカレントディレクトリを意味する -> `ft_split()`が使えない -> `ft_split()`にコロンが連続した時に、カレントディレクトリを挿入する機能を追加した関数`split_path_from_env()`を追加（`ft_split`はsyamashiさんに教わった少しおしゃれな方法で実装！） 
```
A zero-length (null) directory name in the value of PATH indicates the current directory. A null directory name may appear as two adjacent colons, or as an initial or trailing colon.
```
- その他エラーメッセージなどの細かい実装はこちらを参照していただければと思うのですが、自分も完全には理解していないので、軽く見る感じでお願いします！今度一緒に作業する時にでもわかりやすく説明できるようにしておきます！
```
$ cd /minishell/execute/test
$ make
```
- 現状、`argv[0]`に`path`を入れているが、もしかしたらダメかもしれない...実験しておきます
- テストしながら気づいたのですが、最初にノンブロッキングの`read`入れたせいで`cat`コマンドが使えなくなってるかもです笑笑直しておきます！
=> `execvp`の代わりに`execve`の使用

builtin/builtin_export.c
- `export`だけ入力した際にSEGVするケースについて
- 終了ステータスとして環境変数に追加した`?`を、`declare -x`で表示する際に有効な環境変数の数をカウントする`env_vars_len()`が`?`も数に入れてしまっていため、余分なところまで読んでしまい`quick_sort()`中の`ft_strcmp()`に`NULL`が渡されてSEGVしていた。
- そのため、`env_vars_len()`が`?`もカウントしないように修正。
- `export str= str2`と入力した際に以下のようになるケースについて
- 本来、`str2`には`=`がないため、`value`として`NULL`が入る必要があるが、できていなかった。
- `builtin_export()`のループの外で`value=NULL;`と初期化していたため、1個目の`str=`で`set_key_value()`された際に、`value=""`のまま処理が進んでしまい、`str2=""`と空文字が入ってしまっていた。
- `value`初期化をループ内に入れて、毎回`value=NULL`の状態から処理できるようにした。
```bash
$ export str= str2
$ export
...
declare -x str=""
declare -x str2=""
...
```
- `export str= str2 && export | grep str`のテストケースが通る！
- `export`のSEGVしなくなったので、テストしやすいよ！
- `expansion`の`'',""`問題も後でPR投げます〜〜！！（`echo`のせいじゃなかったです。ごめんなさい笑）
=> [軽PR]`export`のバグ修正

env/env.h, env/register_env_var_from_literal.c, execute/execute_init.c, minishell.c
`register_env_var()`のラッパー関数`register_env_var_from_literal()`を作成
こんな感じでリテラルのまま渡せるようになり、コードの簡素化・可読性の向上
```
register_env_var_from_literal("?", NULL, 0, env_vars);
```
=> register_env_var()の文字列リテラルと整数リテラルを取れるラッパー関数の作成

execute/create_envp.c, execute/execute.c, execute/execute.h, execute/execute_init.c, execute/execute_init_utils.c, execute/execute_utils.c, execute/get_cmd_path.c, execute/new_redirect.c, parser/parser.h, wrapper/wrapper.h, wrapper/x.h, wrapper/x_dup.c, wrapper/x_dup2.c, wrapper/x_fork.c, wrapper/x_get_next_line.c, wrapper/x_malloc.c, wrapper/x_pipe.c, wrapper/x_strdup.c, wrapper/x_substr.c
失敗したら、`perror()`して`exit()`する系の関数は`x_*()`と名付けることに決まったので、それに倣っていくつかの関数の作成
標準関数や`libft`関数の後に毎回入っていたエラーチェックがなくなるため、コードの見通しがよくなり可読性が向上！
=> 【軽PR】malloc周りのラッパー関数の追加！

lexer/lexer.c, lexer/lexer.h, lexer/lexer_new_token.c
- [PR#114](https://github.com/tacomea/minishell/pull/114)より `x_malloc(sizeof(t_token))` -> `x_malloc(sizeof(*token))` という形に統一。
- `expander`とかもこれでいきます！！
=> 【超軽PR】`lexer`の`x_malloc()`の引数修正

expander/internal/expander_internal.h
- norm error の解消
- `expander_internal.h`の`LINE_TOO_LONG`を解消した
```
make norm
```
=> expanderの中のNormエラーファイルを修正

expander/internal/expander_wildcard_lst.c
- 使用禁止関数の置き換え
- `strdup` -> `x_strdup`
=> 使用禁止関数の置き換え

expander/expander.c, expander/internal/expander_word_splitting.c
- 以前は、`HEREDOC_NODE`がexpanderに渡された際には、何も展開しないようにしていた。
- しかし、以下のようなケースでは、クオートを除去してからheredocの処理を行わなければならないことが判明した。
```bash
$ cat << T""
> T
$
$ cat << T""
> T
> T""
T
$
```
- また、上記と似たような以下のケースでも、heredocでの展開方法を間違えてしまうと、他のリダイレクトのようにエラーを設定してしまっていた。
```bash
$ echo hello << T""
> T
hello
#NG
$ echo hello << T""
minishell: T"": ambiguous redirect
```
- 上記のエラーケースに対応するため、`expander`における処理を若干修正した。
- `HEREDOC_NODE`が渡された際にも、一部の展開は行うようにした。
もうちょっと上手く書こうとしたらバグり散らかしたので、このぐらいの修正しかできませんでした。。。
=> heredocのdelimのexpandを修正
